### ISSUE TITLE
Make user editable without having to type in password

### ISSUE THREAD

**Issue by hbsock** [CSC444-FormalTigers/TeenServ#35]
Can add lines to the start of the update method on User to remove the :password in parameters if empty.

i.e.
```rb
params[:user].delete(:password) if params[:user][:password].blank?
params[:user].delete(:password_confirmation) if params[:user][:password_confirmation].blank?
```

Anyone's free to add this. Please add some tests to make sure that you can update users when password field is empty.

I'll be doing this myself if it's still up after I finish adding Job applications.

**Comment by jaimeiturriaga** [comment]
I'm working on this now. Ran into a bit of a problem because it kept complaining that the password can't be blank. Turns out the problem was that the validation for password had presence: true. The password normally gets deleted after we update the encrypted password, but if we don't update the password at all, the validation complains since the password attribute is empty. The presence: true validation should instead be moved to the encrypted password attribute, which I'm doing now.
