### ISSUE TITLE
Job model hourly pay should be a decimal number, not just an integer.

### ISSUE THREAD

**Issue by hbsock** [CSC444-FormalTigers/TeenServ#55]
Currently hour pay in the Job model is stored as an integer.
This is awkward when someone may want to pay $14.50 an hour or something...

Should change this entry to store floating point numbers, and modify tests to reflect the changes.

**Comment by jaimeiturriaga** [comment]
So this is slightly more complicated that originally though. sqlite doesn't have a very robust alter table system. So when we try to change_column, what it wants to do is drop the whole table and then create a new table with the old values and the new column.
However since our job table has a lot of foreign key constraints (belongs to user and has many applications), it doesn't want you to drop it.

**Comment by hbsock** [comment]
Alright. Let's just give up on it then.
