### ISSUE TITLE
Jobs list should be surrounded by a table element

### ISSUE THREAD

**Issue by jaimeiturriaga** [CSC444-FormalTigers/TeenServ#65]
Since each job row will have multiple fields, make use of a table to keep these fields aligned, as well as having table headers explaining each field.

**Comment by bathalex210** [comment]
I try to avoid using actual HTML tables. Tables have an inherent style themselves, rows with cells. Although this is what we want to have the problem is that it's difficult to transform the table with CSS - we will need to readjust the layout of the HTML dynamically with CSS for mobile devices. Alternatively, similar to what I have now - we could use DIVs with `float: left` to allow for a column based look. The more modern approach would be to use flexbox which would allow you to create fluid table-like layouts but flex is only supported by [modern browsers](https://caniuse.com/#feat=flexbox).

**Comment by jaimeiturriaga** [comment]
I just want a way to make sure each column of the job index page is flush with each other. For example a column for job name, job poster, application date, and date of job.

**Comment by bathalex210** [comment]
I've changed up the layout a bit since this so I'm not sure if this still applies but we can make the headers evenly spaced by setting a fixed width for each element - right now the text just fills as much space as it can.
