### ISSUE TITLE
focus google map on ip location

### ISSUE THREAD

**Issue by Danielhuxc** [CSC444-FormalTigers/TeenServ#84]
- job creation page
- job listing page

**Comment by hbsock** [comment]
I can't seem to get this working for my browser, so I'll be giving up on this.

**Comment by hbsock** [comment]
Some problems.

1. If there are no jobs near the IP location, you don't see any jobs on the google map. 
2. We didn't have a variable called infoWindow, so if the browser didn't support geocoding current location, there was no output. Please test errors actually get output, not just success.

I've fixed 2. and I will try to fix 1. so that the map will display the jobs near the current location, so for now the current location is disabled.

**Comment by hbsock** [comment]
Getting current location and geolocations of jobs are asynchronous tasks, and honestly I don't want to write code to synchronize this as it's really confusing to read, hence difficult to maintain.

I suggest not bothering to add centering of IP address location due to:
1. Synchronization code with job locations and current location being difficult to read, hence maintain (the code looks sketchy)
2. I don't know enough javascript to know how to test this and adding more javascript features seems like I'm begging for something to go wrong.

**Comment by Danielhuxc** [comment]
IP location centering was trying to solve lack of useful location information. If the solution is asking users to manually input their location, why not just do it at register? 
Also, users are not supposed to see any job if there isn't one near by. A job at another city or continent is useless to the user.

**Comment by hbsock** [comment]
User may not want to use their current location to find where to get to a job. 

For example, if I use this website outside at a coffee shop or something, I obviously don't want the jobs that are near the coffee shop. Hence, user input will be needed most of the time.

If the user doesn't see any jobs on the map, he/she won't know what the map is for. I just think seeing a zoomed in google map to the location is not helpful as compared to showing all the jobs while labeling the input location with a circular marker.

**Comment by Danielhuxc** [comment]
Seriously? Café in another city? That's the common use case you think of? 

Plus, like I said, if you are going with user input why not just put it in registeration so it's only needed once instead of everytime visiting job page?

**Comment by jaimeiturriaga** [comment]
Here's a real world example of something that uses a similar system.
With Yelp, it defaults to your current location by IP. If you want however you can add in a location into a separate search bar and it will center the location on that input. It then filters out restaurants by (no limit), (8km), (4km), (2km), (within 4 blocks).

**Comment by hbsock** [comment]
You don't put location into the user because the user doesn't necessarily want to find jobs near one location all the time.

For example, what if a student goes to a school far from home and wants to find jobs near school and home? In your case @Danielhuxc, the student user would have to edit his/her profile each time they want to find jobs near the location they want.

**Comment by hbsock** [comment]
This is also a really minor thing, so we really shouldn't be spending too much time arguing and actually start implementing missing features that we have to have.

**Comment by Danielhuxc** [comment]
Exactly, the version lastnight was working fine in my opinion where location is default to ip location and user has the option to search as well. However in our case, search is less important compared to yelp because you might want to go out of your way for a good restaurant but not a job far far away. Thus a fixed distance result would've worked fine.

**Comment by hbsock** [comment]
I personally prefer a global view of all jobs, and getting user input for searching for jobs nearby. But hey, that's my opinion. So @Danielhuxc, if you feel very strongly about centering on the user's IP location rather than having a global view of all jobs why don't we get a vote from everyone on Slack.

**Comment by Danielhuxc** [comment]
You're right, it is minor but instead of keeping a design that worked you kinda just took it out without asking for opinion, it could be frustrating sometimes.

**Comment by hbsock** [comment]
Alright. Next time I'll inform whoever wrote the code and discuss before removing their stuff.

**Comment by Danielhuxc** [comment]
I understand that for us devs seeing our site has jobs all over the world is somewhat satisfying, but the question to ask is, is it helpful for users to know there are jobs on another continent?

**Comment by hbsock** [comment]
It's not helpful. I understand Daniel, I'll add it back in then.

**Comment by hbsock** [comment]
Added geolocation usage back in 87c71f94a2e51a654bfcf6dd4e1ed0fc21d5bfc8
